### PR TITLE
Removed "printed" fields from v2 printings

### LINKED ISSUE #669: Do the v2 printing cards need text fields?
We currently have printed_text and stripped_printed_text, but do we need it?  We don't want printings to have different text and have already taken an "update everything at once" approach when making text and rules changes.

Do we need these fields at all in v2?

### PR DESCRIPTION
**Pull request by plural**
Fixes #669

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Was there internal discussion about this? What led to the change?

**Comment by plural** [comment]
yeah, we talked about it on discord a bit.  We aren't using these fields and if we want to really track historical text changes, it's a bit different than what this was doing.

**Comment by distributive** [comment]
Do we want to give the same treatment to the `printed_is_unique` field?

**Comment by plural** [comment]
Yes, i looked and we are currently enforcing that printed_is_unique is the same as is_unique in v1 so i went ahead and removed that here as well.

**Review by distributive — APPROVED** [review]

**Pull request merged**
