### PR TITLE
fix 2 small typos

### PR DESCRIPTION
**Pull request by gereons**
Fix two typos, reported in https://github.com/Alsciende/netrunnerdb/issues/450 and https://github.com/Alsciende/netrunnerdb/issues/449

### CODE REVIEW

**Review by NoahTheDuke — APPROVED** [review]

**Comment by gereons** [comment]
Either Travis or github is acting up, the checks for this and #531 have long passed....

travis status

**Comment by NoahTheDuke** [comment]
Try restarting the tests, maybe that will jog it into reporting correctly

**Comment by gereons** [comment]
Didn't work, unfortunately :( Can you override this manually?

**Comment by NoahTheDuke** [comment]
I don't think I can. This might be the time we move from Alsciende's repo to another one. Lemme chat real quick with the nisei folks and see what we can do.

**Comment by gereons** [comment]
BTW, I just pushed to https://github.com/gereons/netrunner-cards-json/tree/validate/.github/workflows with an example on how to run the validation on github actions instead of Travis.

**Pull request merged**
