### PR TITLE
update text

### PR DESCRIPTION
**Pull request by mankinchi**
This is to handle the issue mentioned here https://github.com/NetrunnerDB/netrunnerdb/issues/623

This is to work with the new way to render Trace tag in https://github.com/NetrunnerDB/netrunnerdb/pull/705

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
I don't think it's a good idea to remove the word "trace" from the text. This should be a repository of the text that is printed on the cards; that we style it in different ways is purely a UI issue.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
As above.

**Comment by plural** [comment]
hiya!  Would you still like to proceed with this?  If so, let us know what you need.  Thanks.  :)

**Comment by mankinchi** [comment]
Hi,

Sorry for the delay. I have been caught up with stuff in life and unable to work on this for awhile. If you want, feel free to abandon this and move forward. I think I will look back into this in 2-3 weeks time

Kind regards,
*
*
*Tri Nguyen*

IT Consultant 

M: 0449 258 526

**Comment by mankinchi** [comment]
so sorry for the disappearance. Personal issue is annoying but resolved. I will look back into this and update it asap 😄

**Comment by plural** [comment]
no worries at all!

**Comment by plural** [comment]
Would you still like to try to do this or have one of us take care of it?

**Comment by plural** [comment]
i ended up taking care of this in #742 .  Thanks for kicking this off, though!

**Pull request closed without merging**
