### PR TITLE
System gateway french translations

### PR DESCRIPTION
**Pull request by canisinhorto**

### CODE REVIEW

**Comment by plural** [comment]
hi there.

I talked with the translation team and we aren't currently using or updating these files.

I'm happy to accept this patch if you want to sync it up for the formatting changes we introduced, though.

**Comment by canisinhorto** [comment]
Hi,  OK i,ll be happy to contribute and add french translation cards . Can
you explain me te new format to sync up with?

**Comment by plural** [comment]
oh, sorry.  I just meant for you to sync and resolve the merge conflicts.  We are automatically enforcing JSON formatting with prettier now.

I would actually hold off on contributing any more translations since these files aren't actively used right now.

Better integrated translation support is on our roadmap, but we're not ready for it yet.

Thanks and sorry for the slow responses!

**Comment by plural** [comment]
if you still want to push this in, please resolve the merge conflicts and we can get this done.

**Comment by plural** [comment]
I haven't heard back so I am going to close this out.  please re-open if you want to do anything with this.

**Pull request closed without merging**
