### PR TITLE
Updated json schema to latest, demonstrate validation with ajv

### PR DESCRIPTION
**Pull request by NoahTheDuke**
This is intended as a jumping off point for building something better. I had hoped to use `ajv` to handle all validation stuff, but it doesn't work well with arrays, only shows the first error instead of multiple errors lol. I think a smarter rewrite of the python validation script is good: instead of globals and printing, maybe an array of errors and pretty-printing them at the end? I don't know, I haven't explored that part because I had full faith that I could bang this out in a couple hours hahahaha

### CODE REVIEW

**Comment by plural** [comment]
what command do you run at the CLI to kick this off?

**Comment by NoahTheDuke** [comment]
What do you mean?

**Comment by plural** [comment]
I had to move this to tests/schema/validate ts so I could get this to run
when I ran npm test.  How were you running it?

Also, since I have you, I have a request for you on discord when you get a
moment. :)

**Comment by NoahTheDuke** [comment]
I will pull out my laptop and check discord! I haven't gotten on a non-work computer since the new baby was born 💀.

I ran `npm test`. It's defined in `package.json` to run all test files in the `test/` directory, so in surprised you had to change it to another directory. I wonder what broke/changed.

**Comment by plural** [comment]
big thanks to Noah for kicking this off.  I'm finishing this up in #656 .

**Pull request closed without merging**
